### PR TITLE
Add node 12 support

### PR DESCRIPTION
**Pull request by Flarna**
No functional change, just update readme, CI and add `NODE_12_0_MODULE_VERSION`.

Refs: #849

### CODE REVIEW

**Comment by mkrufky** [comment]
hmmm.  It looks like appveyor hasn't caught up to node 12 yet.  https://ci.appveyor.com/project/RodVagg/nan

**Comment by Flarna** [comment]
Should I revert the change for appveyor till this is available?

**Comment by mkrufky** [comment]
Being that the PR isn't actually *necessary* for building modules against Node.js 12, I'm inclined to simply wait for Appveyor to include support for Node 12 before merge.  It'll likely happen within days...

**Comment by AlonMiz** [comment]
Any news? Thanks.

**Comment by Flarna** [comment]
Refs: https://github.com/appveyor/ci/issues/2921

**Comment by msimerson** [comment]
For anyone that's anxious for this to be merged, I've created a first step in #853 that adds Travis' windows support. It'll need a little help though to get it working.

**Comment by bnoordhuis** [comment]
Thanks, landed in e512f92.

**Comment by fanatid** [comment]
@bnoordhuis thanks for merge, can you publish new version on npm too?

**Comment by bnoordhuis** [comment]
No real need. Except for the `NODE_12_0_MODULE_VERSION` macro there are no functional changes and consumers of nan normally have no need for that macro. (If you think you do, please explain why.)

**Pull request closed without merging**
