### PR TITLE
fix doc wrt to if Nan::Persistent is copyable

### PR DESCRIPTION
**Pull request by chad3814**
the text is exactly wrong, the code snippet is correct.

### CODE REVIEW

**Comment by kkoopa** [comment]
No, that only applies to Nan::Persistent<T> which is merely a special case of Nan::Persistent<T, M>. The former implicitly uses Nan::NonCopyablePersistentTraits.

**Comment by chad3814** [comment]
This doc is confusing:
https://github.com/nodejs/nan/blob/master/doc/persistent.md#nanpersistent

>### Nan::Persistent
>
>A type of `PersistentBase` which allows copy and assignment. Copy, assignment and destructor behavior is controlled by the traits class `M`.

the sentence "A type of `PersistentBase` which allows copy and assignment." is misleading when the header is just `Nan::Persistent` which defaults to non-copyable.

**Comment by kkoopa** [comment]
But it clearly says the copy, assignment and constructor behavior is controlled by the traits class. The Persistent classes allow for copying and assignment, but they are associated with traits classes and it is those traits classes that either allow or disallow something.

**Comment by chad3814** [comment]
I'm honestly not trying to make trouble, but it is very confusing to me. The default, if you don't specify a trait class is non-copyable. Maybe if it said "A type of `PersistentBase` which can allow copy and assignment with the `Nan::CopyablePersistentTraits` class.

**Comment by kkoopa** [comment]
Under NonCopyablePersistentTraits it says that it is the default traits for Persistent. The definition also shows that the default traits is NonCopyablePersistentTraits. I guess a sentence could be added for Persistent stating that NonCopyablePersistentTraits is the default, with a link there.

**Pull request closed without merging**
