### PR TITLE
Support  for node version 20.17.0

### LINKED ISSUE #973: support for electron 32
With electron 32.0.1 and its underlying v8 version 12.8, there are mulitple errors when building NAN modules:

nan.h(700,39): error C2039: "IdleNotificationDeadline" ist kein Member von "v8::Isolate"
nan.h(2560,8): error C2039: "SetAccessor" ist kein Member von "v8::ObjectTemplate"
nan.h(2654,15): error C2039: "SetAccessor" ist kein Member von "v8::Object"
nan.h(2730,56): error C2440: "<function-style-cast>": "initializer list" kann nicht in "v8::NamedPropertyHandlerConfiguration" konvertiert werden
nan_scriptorigin.h(19,1): error C2664: "v8::ScriptOrigin::ScriptOrigin(v8::Local<v8::Value>,int,int,bool,int,v8::Local<v8::Value>,bool,bool,bool,v8::Local<v8::Data>)" : Konvertierung von Argument 1 von "v8::Isolate *" in "v8::Local<v8::Value>" nicht möglich

### PR DESCRIPTION
**Pull request by toshiyuki-rs**
I modified some implementations to be able to compile for node version 20.17.0.

This modification may resolve #973 .

### CODE REVIEW

**Comment by kkoopa** [comment]
Thank you, I will take a closer look at this in the coming days. However, assuming that this works backwards for relatively old versions of Node.js (I do not know where to reasonably draw the cut-off line), I still have some concerns about the issues mentioned at the end of my [latest comment](https://github.com/nodejs/nan/issues/973#issuecomment-2311173547) on the issue related to (javascript) exception handling. That is, even if it compiles, there might be runtime inconsistencies lurking beneath the surface.

**Comment by agracio** [comment]
Just wanted to add that the issue is also present in upcoming Node.js 23 as this commit [deps: update V8 to 12.8.374.13](https://github.com/nodejs/node/commit/9d7cd9b864cacb72409e693aa26c36338efa05ca) was added to main node branch about a week before https://github.com/nodejs/nan/issues/973 was opened. 

I tested this PR with main node branch (AKA 23) and it resolves the issues with node add-ons that have dependency on Node.js without Electron.

**Comment by farhanlatheef** [comment]
This PR works in Mac and Linux. but not in Windows.

Logs from Windows.
```

C:\Users\farha\.electron-gyp\32.1.2\include\node\v8-internal.h(109,67): error C2589: '(': illegal token on right side of '::' [C:\Users\farha\projects\iohook\build\iohook.vcxproj]
C:\Users\farha\.electron-gyp\32.1.2\include\node\v8-internal.h(108,35): message : This diagnostic occurred in the compiler generated function 'bool v8::internal::SmiTagging<4>::IsValidSmi(T)' [C:\Users\farha\projects\iohook\build\iohook.vcxproj]
C:\Users\farha\.electron-gyp\32.1.2\include\node\v8-internal.h(123,66): error C2589: '(': illegal token on right side of '::' [C:\Users\farha\projects\iohook\build\iohook.vcxproj]
C:\Users\farha\.electron-gyp\32.1.2\include\node\v8-internal.h(123): error C2062: type 'unknown-type' unexpected [C:\Users\farha\projects\iohook\build\iohook.vcxproj]
C:\Users\farha\.electron-gyp\32.1.2\include\node\v8-internal.h(123,1): error C2059: syntax error: ')' [C:\Users\farha\projects\iohook\build\iohook.vcxproj]
C:\Users\farha\.electron-gyp\32.1.2\include\node\v8-function-callback.h(461,61): warning C4003: not enough arguments for function-like macro invocation 'min' [C:\Users\farha\projects\iohook\build\iohook.vcxproj]
C:\Users\farha\.electron-gyp\32.1.2\include\node\v8-function-callback.h(462,61): warning C4003: not enough arguments for function-like macro invocation 'max' [C:\Users\farha\projects\iohook\build\iohook.vcxproj]
C:\Users\farha\.electron-gyp\32.1.2\include\node\v8-function-callback.h(461,61): error C2589: '(': illegal token on right side of '::' [C:\Users\farha\projects\iohook\build\iohook.vcxproj]
C:\Users\farha\.electron-gyp\32.1.2\include\node\v8-function-callback.h(490,62): warning C4003: not enough arguments for function-like macro invocation 'min' [C:\Users\farha\projects\iohook\build\iohook.vcxproj]
C:\Users\farha\.electron-gyp\32.1.2\include\node\v8-function-callback.h(491,62): warning C4003: not enough arguments for function-like macro invocation 'max' [C:\Users\farha\projects\iohook\build\iohook.vcxproj]
C:\Users\farha\.electron-gyp\32.1.2\include\node\v8-function-callback.h(490,62): error C2589: '(': illegal token on right side of '::' [C:\Users\farha\projects\iohook\build\iohook.vcxproj]
C:\Users\farha\projects\iohook\src\iohook.cc(492,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\farha\projects\iohook\build\iohook.vcxproj]
Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
    at ChildProcess.onExit (C:\Users\farha\projects\iohook\node_modules\@electron\rebuild\node_modules\node-gyp\lib\build.js:203:23)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
```

**Comment by kkoopa** [comment]
`test/cpp/methodswithdata.cpp:174` and `test/cpp/methodswithdata.cpp:180` `SetAccessor` seem to fail on almost every entry in the test matrix

**Comment by agracio** [comment]
@toshiyuki-rs Would you be able to take a look at failing tests by any chance?

**Comment by toshiyuki-rs** [comment]
@agracio

> Would you be able to take a look at failing tests by any chance?

Yes, I will check test/cpp/methodswithdata.cpp and test/cpp/methodswithdata.cpp

**Comment by kkoopa** [comment]
Wonderful, this is looking a lot better: https://ci.appveyor.com/project/RodVagg/nan/builds/50749401 I shall take a closer look once it has finished.

**Comment by kkoopa** [comment]
Looks great, I only have one small request: Could you redo the `IdleNotification` part like the corresponding commit I had here? https://github.com/nodejs/nan/pull/974 That is, make it a dummy function that only returns true, mark them all as `NAN_DEPRECATED` and apply the documentation updates?

**Comment by SchizoDuckie** [comment]
Can confirm this pr allows me to compile `node_sleep` on a Raspi (aarch64) running Debian Bookworm with `node v20.18.0` and `node-gyp v10.2.0`

**Comment by toshiyuki-rs** [comment]
I made IdleNotification deprecated and update documents.

**Comment by kkoopa** [comment]
Thank you. I will wait for the results of the regression tests to finish, then merge this and push a new release.

**Comment by danielweck** [comment]
Unfortunately NAN `v2.21.0` still fails with Electron (`v32.2.0`):

https://github.com/nodejs/nan/issues/973#issuecomment-2404892721

**Comment by agracio** [comment]
Can confirm that it fails while the initial fork from @toshiyuki-rs worked it appears that both the fork and latest release no longer compile Electron 32.

**Pull request merged**
