### PR TITLE
Update callback.md

### PR DESCRIPTION
**Pull request by sesh-kebab**
callback isn't a pointer. Member access operator is incorrect.

### CODE REVIEW

**Comment by sesh-kebab** [comment]
This is documentation fix - but the builds have failed. @rvagg first time doing a pull request; would you please be able to help with how to work through this?

**Comment by kkoopa** [comment]
Some of them fail sometimes due to external reasons. It does not matter here as it is only documentation. Don't worry.

**Comment by sesh-kebab** [comment]
@kkoopa cool - thanks! :)

**Comment by rvagg** [comment]
merged @ 042068e, thanks @sesh-kebab!

**Pull request closed without merging**
