### PR TITLE
Check for C++11 compiler first

### PR DESCRIPTION
**Pull request by agnat**
As discussed in #448.

### CODE REVIEW

**Comment by rvagg** [comment]
lgtm

**Comment by greenboxal** [comment]
It seems to be worse than that. I can't build nan 2.0.9 using GCC 4.8 against node 0.12 or lower.

https://travis-ci.org/pagarme/node-rsa-keygen/jobs/80027572

There's a lot of errors regarding double brackets on `pre43` code. I fear that this could extend to v8 code also, breaking any possibility of using newer compilers with it.

**Comment by kkoopa** [comment]
Something's wrong under AppVeyor. Does msvs2013 not set the proper define? It is C++11-capable, as it can compile the code, so something's wrong with the detection logic.

**Comment by kkoopa** [comment]
Yes, typical Microsoft... Never get anything done right.
https://connect.microsoft.com/VisualStudio/feedback/details/763051/a-value-of-predefined-macro-cplusplus-is-still-199711l

> Thanks for your feedback. Could you please provide some screenshots to help us better understand this scenario?

need to add `#ifdef _MSC_VER && _MSC_VER < 1800`

**Comment by agnat** [comment]
Really?!?...wow... just... wow. lol.

Just let me real quick...

**Comment by agnat** [comment]
Like this?

**Comment by kkoopa** [comment]
The jury is still out, but I guess the outcome will be pleasing.

**Comment by kkoopa** [comment]
Seems to work.

**Comment by brodybits** [comment]
We should also add:
```c++
#define NODE_4_00_MODULE_VERSION 46
```
see #477

**Comment by kkoopa** [comment]
Yes, that should be added, although it ought to be `NODE_4_0_MODULE_VERSION`.

**Comment by kkoopa** [comment]
Merged as 48cc1d8543aff67c2181c73caddcc94ba8fd2230

**Pull request closed without merging**
