### PR TITLE
Update asyncprogressworkerstream.cpp

### PR DESCRIPTION
**Pull request by AndyleeSharp**
size is the number of objects, rather than the number of bytes

### CODE REVIEW

**Comment by kkoopa** [comment]
Yes, it seems you are correct, which hints at possible bugs in the implementation or a badly named parameter. I will to take a closer look.

**Comment by kkoopa** [comment]
Apart from the bug you found in the test, the actual implementation only suffers from a badly named parameter. I will rename `size` to `count` in the implementation and update the documentation when merging this commit.

**Comment by AndyleeSharp** [comment]
yes, _count_ is better

**Comment by kkoopa** [comment]
Merged as 9ef7d4dc69e23f7f8fc52f40eced5323db201c05

**Pull request closed without merging**
