### PR TITLE
Fix new versions not to use WeakCallbackInfo::IsFirstPass

### PR DESCRIPTION
**Pull request by kkoopa**
Follow-up to #568.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
LGTM, I think.

**Comment by kkoopa** [comment]
Good. Thanks for looking through it. This was the least invasive solution I could come up with. It should even have better performance than the old implementation, thanks to dead code elimination. CI also passes, but in somehow the hook part showing CI status in PRs has disappeared in the last months.
I'll merge this and the related PR this week and publish a new patch version.

@rvagg Could you figure out what's what with the Travis and AppVeyor hooks for PRs?

**Comment by rvagg** [comment]
Unfortunately the nodejs org doesn't allow third-party applications, it's been a policy for a while but tbh I don't recall how it started or exactly what the justification is. That's why Travis and AppVeyor can't post status back via the GH API.

**Comment by kkoopa** [comment]
Aha, well that explains why it stopped working. Cannot access be granted for specific repositories? The current state is quite error prone, as it is easy to forget checking builds manually.

**Comment by bnoordhuis** [comment]
It depends on the permissions that the third-party application wants.  In the case of Travis CI, it wanted (and presumably still wants) permissions that lets it access private repositories.  Because our private repositories contain sensitive information, and because we can't trust a third-party not to get hacked, that makes it a no-go.

**Pull request merged**
