### PR TITLE
Private Accessors

### PR DESCRIPTION
**Pull request by kkoopa**
This replaces the defunct #599

### CODE REVIEW

**Comment by JoshuaWise** [comment]
YESSSSSS. I was just about to create a new pull request like this myself today, haha.

**Comment by mdlavin** [comment]
I'd love to see these methods merged so that support node 7 in native modules is easy. Is there anything left to be done?  I have a couple days of time that I could try to help move this along.

**Comment by kkoopa** [comment]
The pull request must pass code review by another collaborator before it can be merged.

**Comment by kkoopa** [comment]
Thanks. I'll try to add such tests before merging.

**Comment by kkoopa** [comment]
Merged as a86255cb357e8ad8ccbf1f6a4a901c921e39a178

**Pull request closed without merging**
