### PR TITLE
Reimplement ObjectWrap from scratch to prevent memory leaks.

### LINKED ISSUE #389: Is nan v2.0.0 leaking memory?
I'm in the process of migrating the [epoll](https://github.com/fivdi/epoll) module from nan v1.8.4 to nan v2.0.0. Everything is looking ok except for memory usage. There's an epoll test called [brute-force-leak-check.js](https://github.com/fivdi/epoll/blob/master/test/brute-force-leak-check.js). This test is used to create millions of objects and while it's running the memory usage is observed to see if everything looks ok. With `Node.js v0.10.40` and `nan v1.8.4` memory usage is extremely stable and everything looks good. With `Node.js v0.10.40` and `nan v2.0.0` memory usage keeps increasing and eventually the test will terminate with:

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

I can't figure out where the problem is and wrote the following test to see if the problem is in the `epoll` code or perhaps somewhere else:

```
const testRoot = require('path').resolve(__dirname, '..')
  , bindings = require('bindings')({ module_root: testRoot, bindings: 'objectwraphandle' });

var i, obj;

for (i = 1; i <= 1e9; i += 1) {
  obj = new bindings.MyObject(i);
  if (i % 1e6 === 0) {
    console.log(i);
  }
}
```

This test is similar to the `epoll` `brute-force-leak-check` but creates millions of `nan` `MyObject` instances instead ([objectwraphandle.cpp](https://github.com/nodejs/nan/blob/master/test/cpp/objectwraphandle.cpp)).

If this test is placed in the `nan` `test\js` folder and run from there, the same issue can be seen. With `Node.js v0.10.40` and `nan v1.8.4` memory usage is extremely stable and everything looks good. With `Node.js v0.10.40` and `nan v2.0.0` memory usage keeps increasing and eventually the test will terminate after throwing an instance of `std::bad_alloc`.

Unfortunately, it may take a long time for `std::bad_alloc` to be thrown, even on a machine with only 2GB of RAM, but the constant increase in memory usage is immediately visible. This is the followed by swapping to the hard-disk after a relatively short period of time.
 
Additional information:
```
$ node -v
v0.10.40
$ uname -a
Linux linuxbox 3.13.0-58-generic #97-Ubuntu SMP Wed Jul 8 02:56:50 UTC 2015 i686 i686 i686 GNU/Linux
$ 
```

Is the test a little too stupid/synthetic or is there an issue somewhere?

### PR DESCRIPTION
**Pull request by kkoopa**
Part of #389.

### CODE REVIEW

**Comment by kkoopa** [comment]
I can't figure out why returnvalue keeps failing consistently on 0.10.40 at AppVeyor.

**Comment by mathiask88** [comment]
@kkoopa Can't reproduce (Win10/VS15). Some strange appveyor behavior.

**Comment by kkoopa** [comment]
I can't reproduce it myself either.

**Comment by kkoopa** [comment]
@bnoordhuis Can you review this? Something is still leaking somewhere, but I can't see why it would be this.

**Comment by bnoordhuis** [comment]
I'll (try to) take a look today at this and #389.

**Comment by kkoopa** [comment]
I'll include this in 2.0.1, as it resolves part of the problem. Just have to update the documentation of ObjectWrap.

**Pull request merged**
