### PR TITLE
deps: adapt to V8 7.0

### PR DESCRIPTION
**Pull request by refack**
Fixes: https://github.com/nodejs/node/issues/23122

~Also updates dependencies~

### CODE REVIEW

**Comment by addaleax** [comment]
@rvagg @kkoopa Can we get a release out with this asap? I think that would be a really good step forward for un-breaking CITGM…

**Comment by chjj** [comment]
Still receiving deprecation warnings with 2.11.1:

```
../../nan/nan.h:1064:78: warning: v8::Local<v8::String> v8::Value::ToString(v8::Isolate*) const is deprecated: Use maybe version [-Wdeprecated-declarations]
       v8::Local<v8::String> string = from->ToString(v8::Isolate::GetCurrent());
```

It appears that:

``` cc
v8::Local<v8::String> v8::Value::ToString(v8::Isolate*) const
``` 

is also deprecated.

Shouldn't it be doing something like:

``` cc
v8::Local<v8::String> string = from->ToString(v8::Isolate::GetCurrent()->GetCurrentContext()).FromMaybe(v8::Local<v8::String>());
```

Not sure.

cc @addaleax

**Comment by Flarna** [comment]
@chjj I think #811 addresses these warnings

**Comment by chjj** [comment]
@Flarna, ah, thanks. Didn't see that.

All this v8 stuff is driving me nuts. I should really switch to NAPI.

**Pull request merged**
