### PR TITLE
replace SetAccessor -> SetNativeDataProperty

### LINKED ISSUE #973: support for electron 32
With electron 32.0.1 and its underlying v8 version 12.8, there are mulitple errors when building NAN modules:

nan.h(700,39): error C2039: "IdleNotificationDeadline" ist kein Member von "v8::Isolate"
nan.h(2560,8): error C2039: "SetAccessor" ist kein Member von "v8::ObjectTemplate"
nan.h(2654,15): error C2039: "SetAccessor" ist kein Member von "v8::Object"
nan.h(2730,56): error C2440: "<function-style-cast>": "initializer list" kann nicht in "v8::NamedPropertyHandlerConfiguration" konvertiert werden
nan_scriptorigin.h(19,1): error C2664: "v8::ScriptOrigin::ScriptOrigin(v8::Local<v8::Value>,int,int,bool,int,v8::Local<v8::Value>,bool,bool,bool,v8::Local<v8::Data>)" : Konvertierung von Argument 1 von "v8::Isolate *" in "v8::Local<v8::Value>" nicht möglich

### PR DESCRIPTION
**Pull request by kkoopa**
This should finally close #973. I will let the tests run, expect a release tomorrow.

### CODE REVIEW

**Comment by bugsounet** [comment]
Hi, just tested with electron v32.2.0 and electron-rebuild with node-pty, drivelist, node-gpiod, usb, node-detector

Result:

```
✔ Rebuild Complete
```

**Comment by agracio** [comment]
Works for Electron 29+ but fails for previous versions based on Node.js 18. Looks like test failures reflect that issue.

```
error C2665: 'v8::ObjectTemplate::SetAccessor': no ove rloaded function could convert all the argument types
```

**Comment by kkoopa** [comment]
Node 18 works fine: https://ci.appveyor.com/project/RodVagg/nan/builds/50770411 Electron's frankenbuilds are not Node.js.

**Comment by agracio** [comment]
I am fully aware of that and that was not really a complaint since Electron versions below 30 are out of support. As per my comment native modules using Node.js 16 and 18 that do not rely on Electron build perfectly fine.

**Comment by agracio** [comment]
Just an observation - should Node 22 be also included in AppVeyor build matrix?

**Comment by agracio** [comment]
Apologies for spamming so many comments. Tested building my native (non Electron) modules using node.exe 23.0.0 built from main branch and this PR - success.

**Comment by agracio** [comment]
Understandable, I can relate.

**Pull request merged**
