### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by abetomo**
The link of `io.js-3.0` was 404, so I modified it to ~~`node-8.0`~~ `io.js-3.3`

### CODE REVIEW

**Comment by kkoopa** [comment]
This will not work as the anchor links do not match. It seems io.js-3.3 docs are still up and there at least the majority of anchor tags seem to work.

**Comment by abetomo** [comment]
Should I rewrite it to `io.js-3.3`?

**Comment by kkoopa** [comment]
Unless you want to update all the link anchors to match those in the node 8 documentation, yes. This should involve less effort.

**Comment by kkoopa** [comment]
Thank you for noticing and fixing this.

**Pull request merged**
