### PR TITLE
Cache ObjectTemplates

### PR DESCRIPTION
**Pull request by kkoopa**
It might help to cache these.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
Is it intentional that every source file gets its own cache?

**Comment by kkoopa** [comment]
Not really. It would be better to have one set per application.

**Comment by kkoopa** [comment]
I added a `Cache` structure with a dummy template parameter.

**Comment by kkoopa** [comment]
What, like this?

```diff
diff --git a/test/cpp/multifile1.cpp b/test/cpp/multifile1.cpp
index dc35eda..f6590cb 100644
--- a/test/cpp/multifile1.cpp
+++ b/test/cpp/multifile1.cpp
@@ -24,6 +24,10 @@ NAN_MODULE_INIT(Init) {
     , New<v8::String>("s").ToLocalChecked()
     , New<v8::FunctionTemplate>(ReturnInt)->GetFunction()
   );
+  Set(target
+    , New<v8::String>("p").ToLocalChecked()
+    , New<v8::FunctionTemplate>(ReturnTest)->GetFunction()
+  );
 }

 NODE_MODULE(multifile, Init)
diff --git a/test/cpp/multifile2.cpp b/test/cpp/multifile2.cpp
index 69ded2f..f90e8d8 100644
--- a/test/cpp/multifile2.cpp
+++ b/test/cpp/multifile2.cpp
@@ -14,3 +14,15 @@ NAN_METHOD(ReturnString) {
   v8::Local<v8::String> s = New(*Utf8String(info[0])).ToLocalChecked();
   info.GetReturnValue().Set(s);
 }
+
+NAN_METHOD(ReturnTrue) {
+  info.GetReturnValue().Set(true);
+}
+
+NAN_METHOD(ReturnTest) {
+  v8::Local<v8::Function> f =
+      Nan::GetFunction(New<v8::FunctionTemplate>(ReturnTrue)).ToLocalChecked();
+  info.GetReturnValue().Set(
+      Nan::Call(f, Nan::GetCurrentContext()->Global(), 0, 0).ToLocalChecked());
+}
+
diff --git a/test/cpp/multifile2.h b/test/cpp/multifile2.h
index 5f229c5..989b502 100644
--- a/test/cpp/multifile2.h
+++ b/test/cpp/multifile2.h
@@ -14,5 +14,7 @@
 using namespace Nan;  // NOLINT(build/namespaces)

 NAN_METHOD(ReturnString);
+NAN_METHOD(ReturnTest);
+NAN_METHOD(ReturnTrue);

 #endif  // TEST_CPP_MULTIFILE2_H_
diff --git a/test/js/multifile-test.js b/test/js/multifile-test.js
index 8b21a53..ad11736 100644
--- a/test/js/multifile-test.js
+++ b/test/js/multifile-test.js
@@ -14,12 +14,15 @@ const test     = require('tap').test
 // just to test that there aren't any conflicts from including nan.h
 // more than once in project files
 test('multifile', function (t) {
-  t.plan(4);
+  t.plan(6);

   var r = bindings.r,
-      s = bindings.s;
+      s = bindings.s,
+      p = bindings.p;
   t.type(r, 'function');
   t.type(s, 'function');
+  t.type(p, 'function');
   t.equal(r('a string value'), 'a string value');
   t.equal(s(), 1337);
+  t.ok(p());
 });
```
```sh
kkoopa@ubuntu:~/dev/nan$ objdump -t test/build/Release/multifile.node | c++filt | grep 'Cache'
00000000002041b0 u     O .bss   0000000000000008              guard variable for Nan::imp::Cache<void>::propertyTemplate
00000000002041e0 u     O .bss   0000000000000008              Nan::imp::Cache<void>::functionTemplate
00000000002041b8 u     O .bss   0000000000000008              guard variable for Nan::imp::Cache<void>::accessorTemplate
00000000002041d0 u     O .bss   0000000000000008              Nan::imp::Cache<void>::propertyTemplate
00000000002041c8 u     O .bss   0000000000000008              Nan::imp::Cache<void>::indexPropertyTemplate
00000000002041d8 u     O .bss   0000000000000008              Nan::imp::Cache<void>::accessorTemplate
00000000002041a8 u     O .bss   0000000000000008              guard variable for Nan::imp::Cache<void>::indexPropertyTemplate
00000000002041c0 u     O .bss   0000000000000008              guard variable for Nan::imp::Cache<void>::functionTemplate
```

**Comment by bnoordhuis** [comment]
I thought you were seeing linker smarts that stopped it from running afoul of the One Definition Rule but it turns out it's guaranteed by the standard:

> An explicit specialization of a static data member of a template is a definition if the declaration includes an initializer; otherwise, it is a declaration.

(I.e., it's a declaration here.  Things could still go south if two files saw different definitions of `Nan::Persistent` or `v8::ObjectTemplate`, e.g., through preprocessor defines - but I digress.)

Okay, that objection is withdrawn.  It does however make it impossible to use NAN from another thread and I know of at least one add-on that does that by means of a new isolate.

It also introduces an ABI of a kind because you can't change or reorder fields without recompiling everything that uses it.  That's something you can't really enforce on your downstream users.

**Pull request closed without merging**
