### PR TITLE
Add NanErrnoException

### PR DESCRIPTION
**Pull request by sam-github**
PR is modelled on 81d4a2c0e04, which had neither docs nor tests, so maybe its too small to need them?

### CODE REVIEW

**Comment by kkoopa** [comment]
Thanks. Looks good. Docs were going to be added at release (essentially just saying that it is equivalent to the node function). I can add that documentation myself.

Tests are nice, but not strictly necessary for such a simple construct as a straight wrapper, although good to have in case of regressions. Here, the test is mostly that it still compiles on all platforms, which it seems to do.

**Comment by sam-github** [comment]
Great, thanks @kkoopa, any chance of getting this into 1.9? I'm trying to get node-fs-ext to not spew warnings during installation, they make people nervous.

**Comment by kkoopa** [comment]
Sure, I'll include it.

**Comment by kkoopa** [comment]
Committed in dd87d9e9280cdf27488377b7d6a8cc1d6bd1a34d

**Pull request closed without merging**
