### PR TITLE
Test on Node.js 4.0.

### PR DESCRIPTION
**Pull request by kkoopa**
I don't think it's worth testing on io.js any more.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
I speculate there will be one or two more io.js v3 releases so I wouldn't axe it from the test matrix just yet.

**Comment by kkoopa** [comment]
Alright. I'll update this and add it back in a couple of days, when the CI environments actually can install v4.

**Comment by wadey** [comment]
Node v4 works on both appveyor now:

- https://ci.appveyor.com/project/WadeSimmons/node-microtime/build/48
- https://github.com/wadey/node-microtime/blob/master/.appveyor.yml#L39

**Comment by kkoopa** [comment]
Excellent.

**Pull request closed without merging**
