### PR TITLE
Add Callback::Reset

### PR DESCRIPTION
**Pull request by kkoopa**
This is useful if you want to set and unset a `Callback`.

CI: https://travis-ci.org/nodejs/nan/builds/137235515

### CODE REVIEW

**Comment by rvagg** [comment]
lgtm, but maybe `Reset` would be more familiar?

**Comment by kkoopa** [comment]
I thought of Reset, but decided not to. Reset should also allow setting the function, this would make SetFunction useless, removing SetFunction would be a major change.

It could also be thought of as clearing the underlying Persistent, which it does not.

As such, I thought Clear was the better name for the time being.

**Comment by bnoordhuis** [comment]
You could add a Reset() overload that takes a `Local<Function>` and make SetFunction() a deprecated alias.  Not saying you should, just that it's possible. :-)

**Comment by kkoopa** [comment]
I was thinking of doing that in autumn or so for the next major, sans deprecation. At the same time parts should be maybefied and more stuff fixed overall. This is a stopgap measure.

I also don't remember why the Function is stored as a property on a Persistent Object. Why is it not stored directly? If that were the case, Reset would be wholly sensible.

**Comment by kkoopa** [comment]
There, now it is called `Reset`, and the `Callback` is cleaner.

**Comment by bnoordhuis** [comment]
LGTM

**Pull request merged**
